import { ReservationCheckForm, ReservationBranchCards } from "../components/ReservationForm";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProcessGallery } from "../components/ProcessGallery";
import { ProductCatalog } from "../components/ProductCatalog";
import { PageHead, Shell, SubHero } from "../components/SiteShell";
import { allSlugs, menus, notices, processes } from "../site-data";

export function generateStaticParams(){return allSlugs.map(slug=>({slug}))}
const groupFor=(slug:string)=>menus.find(g=>g.items.some(i=>i.href===`/${slug}`))!;
const titleFor=(slug:string)=>groupFor(slug)?.items.find(i=>i.href===`/${slug}`)?.label??"";

const FacilityTable=()=> <><div className="fact-grid"><div><b>위치</b><span>전남광주 장성군 장성읍 단풍로 226-22</span></div><div><b>운영시간</b><span>평일 09:00~18:00</span></div><div><b>시설규모</b><span>가공·포장·교육 공간</span></div><div><b>주요시설</b><span>전처리실, 잼·조청·젤리 제조실, 잼·조청·젤리 충진실, 과즙포장실, 후살균냉각실, 제환실, 외포장실, 기계실·냉동기</span></div></div><h3 className="content-h3">주요 장비 현황</h3><div className="data-table"><div><b>실명</b><b>장비명</b></div>{[["전처리실","과일 박피기, 과일 파쇄기, 3단 세척기, 버블세척기, 비타민 C 공급장치, 퓨레포집 탱크, 모노 플렉스 펌프, 세미기, 당화탱크, 쌀 분쇄기, 식품 원심분리기, 살균교반탱크, 원심분리기, 토마토·블루베리 분쇄기, 스크류착즙기"],["잼·조청·젤리 제조실","진공농축장치, 진공농축기"],["잼·조청·젤리 충진실","피스톤 충진기, 캡핑기, 충진기, 작업 테이블, 세병기, 파이프형 금속검출기"],["과즙포장실","저장액 이송펌프, 스탠딩 파우치 충진기, 후살균기, 롤포장기"],["후살균냉각실","잼병건조기, 라벨부착기"],["제환실","동결건조기, 제습건조기, 열풍건조기, 분쇄기, 과립성형기"],["외포장실","금속검출기, 업소용 냉장고, 밴드실러"],["기계실·냉동기","스팀보일러 장치, 냉동기 장치, 에어콤프레셔 장치"]].map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span></div>)}</div></>;

function Content({slug}:{slug:string}){
 if(slug==="about") return <div className="about-layout"><div className="about-badge">SINCE<br/><b>2026</b></div><div><p className="lead">장성의 농산물에 기술과 아이디어를 더해<br/><strong>농업의 새로운 가능성</strong>을 만듭니다.</p><p>장성농산물가공센터는 지역에서 생산된 농산물의 부가가치를 높이고, 농업인의 가공 창업과 안정적인 제품 생산을 지원하기 위한 공동 가공시설입니다.</p><p>개별 농가의 설비 투자 부담을 줄이고 시제품 개발, 품목제조보고, 위생관리, 포장과 상품화까지 체계적으로 지원하여 지역 농산업의 지속 가능한 성장을 돕습니다.</p><div className="value-cards"><div><b>01</b><h3>제품 개발</h3><p>지역 농산물을 활용한 시제품 연구</p></div><div><b>02</b><h3>공동 생산</h3><p>안전한 시설과 전문 장비 지원</p></div><div><b>03</b><h3>창업 지원</h3><p>교육부터 상품화까지 단계별 지원</p></div></div></div></div>;
 if(slug==="facilities") return <FacilityTable/>;
 if(slug==="business") return <><p className="lead center">농산물의 생산을 넘어 상품화와 창업까지<br/><strong>현장 중심의 가공 지원</strong>을 제공합니다.</p><div className="business-grid">{[["01","가공창업 교육","기초·심화 교육을 통해 농업인의 가공 역량을 키웁니다."],["02","시제품 개발","지역 특산물을 활용한 레시피와 제조공정을 연구합니다."],["03","상품화 지원","품목제조보고, 포장, 표시사항 등 제품 출시를 지원합니다."],["04","HACCP 관리","위생관리와 시설 점검으로 안전한 생산환경을 유지합니다."]].map(x=><article key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></>;
 if(slug==="products") return <><div className="report-box"><b>품목제조보고</b><span>잼류 · 퓨레 · 음료</span></div><ProductCatalog/></>;
 if(slug==="location") return <><a className="map-placeholder" href="https://map.naver.com/p/search/장성군농업기술센터농산물가공지원센터" target="_blank" rel="noopener noreferrer"><span>장성농산물가공센터</span><b>네이버 지도에서 보기 ↗</b><p>전남 장성군 장성읍 단풍로 226-22 · 클릭하면 네이버 지도가 새 창으로 열립니다.</p></a><div className="location-info"><div><small>ADDRESS</small><h3>전남 장성군 장성읍 단풍로 226-22</h3></div><div><small>CONTACT</small><h3>061-000-0000</h3></div></div><h3 className="content-h3">대중교통 이용안내</h3><div className="transport"><article><b>BUS</b><h4>버스 이용 시</h4><p>장성공용버스터미널에서 농업기술센터 방면 버스를 이용해 주세요.</p></article><article><b>CAR</b><h4>자가용 이용 시</h4><p>내비게이션에서 '장성군농업기술센터농산물가공지원센터'를 검색해 주세요.</p></article></div></>;
 if(slug==="guide") return <><h3 className="content-h3">시설이용</h3><div className="data-table"><div><b>구분</b><b>내용</b></div>{[["이용기간","매주 월~금요일 09:00~18:00 (공휴일 제외)"],["이용대상","관내 농업인 및 농업법인, 식품 판매 관련 허가 사업자"],["사용예약","시설 이용 희망일 전월 지정 기간에 홈페이지 예약"]].map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span></div>)}</div><h3 className="content-h3">이용방법</h3><div className="guide-steps">{[["01","사전상담","가공 품목과 원료, 시설 이용 가능 여부를 상담합니다."],["02","회원등록","이용자 정보와 필수 제출서류를 등록합니다."],["03","원료검사","잔류농약 등 필요한 원료검사를 완료합니다."],["04","온라인 예약","가공 품목과 희망 날짜를 선택해 예약합니다."],["05","제품 생산","담당자 안내에 따라 원료 입고부터 출고까지 참여합니다."]].map(x=><article key={x[0]}><b>{x[0]}</b><h4>{x[1]}</h4><p>{x[2]}</p></article>)}</div></>;
 if(slug==="process") return <div className="process-list">{processes.map((process,i)=><article key={process.name}><div className="process-heading"><small>PROCESS {String(i+1).padStart(2,"0")}</small><h3>{process.name}</h3><p>{process.category}</p></div><ProcessGallery name={process.name} images={process.images}/><ol>{process.steps.map((step,j)=><li key={step}><b>{j+1}</b><span>{step}</span></li>)}</ol></article>)}</div>;
 if(slug==="legal") return <><div className="legal-intro"><b>식품위생법에 따른 준수사항</b><p>안전한 식품 생산을 위해 영업자와 시설 이용자는 관련 법령 및 센터 운영지침을 준수해야 합니다.</p></div>{[["자가품질검사","제품 유형별 검사 주기에 따라 성상, 이물, 세균수, 대장균군 등의 검사를 실시합니다."],["건강진단","식품 제조에 직접 종사하는 이용자는 유효한 건강진단결과서를 제출해야 합니다."],["위생교육","시설 이용 전 개인위생, 교차오염 방지, 장비 안전수칙 교육을 이수해야 합니다."],["표시사항","제품명, 원재료명, 내용량, 소비기한, 보관방법 등 법정 표시사항을 준수합니다."]].map(x=><section className="legal-section" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></section>)}</>;
 if(slug==="reservation"||slug==="reservation-check") return <Reservation check={slug.endsWith("check")}/>;
 if(slug==="fees") return <><div className="fee-note">단위: 원 · 아래 금액은 화면 구성을 위한 예시이며 조례 확정 후 교체해야 합니다.</div><div className="data-table fees"><div><b>가공품목</b><b>단가기준</b><b>사용료</b></div>{[["과채주스","1일","100,000"],["액상차","1일","100,000"],["분말류","1일","20,000"],["잼류","1일","22,000"],["제과·제빵","1일","10,000"]].map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><b>{r[2]}</b></div>)}</div></>;
 if(slug==="notices"||slug==="education") return <Board education={slug==="education"}/>;
 return null;
}

function Reservation({check}:{check:boolean}){return <><div className="reservation-intro"><span>ONLINE RESERVATION</span><h3>{check?"예약 내역을 확인하세요":"이용할 시설을 선택하세요"}</h3><p>{check?"예약자 정보와 신청번호로 접수 상태를 조회할 수 있습니다.":"센터 운영일정과 품목별 가공 가능 여부를 확인한 후 신청해 주세요."}</p></div>{check?<form className="check-form"><label>예약자명<input placeholder="예약자 이름"/></label><label>연락처<input placeholder="010-0000-0000"/></label><button type="button">예약 조회</button></form>:<div className="branch-cards"><article><small>PROCESSING CENTER</small><h3>가공센터</h3><p>과채주스 · 액상차 · 잼류 · 분말류</p><span>전월 지정 예약기간 접수</span><button>예약하기 →</button></article><article><small>EDUCATION FACILITY</small><h3>교육·실습실</h3><p>가공창업 교육 · 시제품 실습</p><span>교육 일정에 따라 접수</span><button>예약하기 →</button></article></div>}</>}

function Board({education}:{education:boolean}){const rows=education?[["1","2026년 농산물 가공창업 기초교육 안내","센터관리자","2026-07-10","88"],["2","식품위생 및 HACCP 실무교육 모집","센터관리자","2026-06-02","71"]]:notices.map((n,i)=>[String(notices.length-i),n[1],n[2],n[3],n[4]]);return <><form className="board-search"><select><option>제목</option><option>내용</option><option>제목+내용</option></select><input placeholder="검색어를 입력하세요"/><button type="button">검색</button></form><div className="board"><div className="board-row head"><b>번호</b><b>제목</b><b>작성자</b><b>날짜</b><b>조회</b></div>{rows.map(r=><Link href="#" className="board-row" key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><span>{r[2]}</span><time>{r[3]}</time><span>{r[4]}</span></Link>)}</div><div className="pagination"><b>1</b></div></>}

export default async function SubPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!allSlugs.includes(slug))notFound();const group=groupFor(slug);const title=titleFor(slug);return <Shell><main><SubHero group={group.title}/><div className="container sub-content"><PageHead group={group.title} title={title}/><Content slug={slug}/></div></main></Shell>}
